{{- if eq .Values.ambient.strategy "daemonset" -}}
apiVersion: apps/v1
kind: "DaemonSet"
metadata:
  name: {{ include "dapr-ambient.fullname" . }}
  labels:
    {{- include "dapr-ambient.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "dapr-ambient.selectorLabels" . | nindent 6 }}
{{ include "daemon-deploy-shared" . }}
{{- end -}}
